version: '3'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    network_mode: host

  start:
    build:
      context: .
      dockerfile: Dockerfile.start
    restart: always
    network_mode: host
